version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - '50:d6:c4:60:c0:5c:6f:89:81:ae:c3:c0:4d:32:ab:e3'
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
